server:
  port: 8082

spring:
  application:
    name: 1-2-LOGSTICS-SERVICE
  profiles:
    active: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://www.clines.club:2222/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
oomall:
  #最大付款时间, 单位分钟
  maxpaytime: 30
  #redis缓存失效时间，单位分钟
  redisexpiretime: 1
  #预提库存数量
  predeductQty: 3

